### ISSUE TITLE
Spin Now working with Mootools

### ISSUE THREAD

**Issue by harshek** [Gix075/jqueryIntroLoader#2]
Hi,

My console says this error
(intermediate value).spin is not a function

On this below line
plugin.spinner = new Spinner(spinOpt).spin();

So how i can resolve this error. Can i get email for this solution.

**Comment by Gix075** [comment]
Probably it's a conflict with Mootools. Have you load jQuery in no-conflict mode?

**Comment by harshek** [comment]
Yes,

We are loading jquery in no-conflict mode.

On Tue, Feb 24, 2015 at 7:07 PM, Gix075 <notifications@github.com> wrote:

> Probably it's a conflict with Mootools. Have you load jQuery in
> no-conflict mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gix075/jqueryIntroLoader/issues/2#issuecomment-75756913>
> .
>



-- 
Harshek Jain
(Web Programmer)
Directive Technology Incorporated
<http://www.directive.com>
www.directive.com

**Comment by Gix075** [comment]
I don't know, I have tested just now the plugin on codepen with a copy of mootools and jquery included at same time, and it work. 
http://codepen.io/Gix075/pen/qEYMoY

If you have a public link of your project I will try to help you
