### ISSUE TITLE
Custom spinner

### ISSUE THREAD

**Issue by pixedelic** [Gix075/jqueryIntroLoader#4]
Hi, great script, thank you for sharing!

I would like to use an SVG as spinner, is that possible? I tried to put it into <code>div#element</code>, via html and also via jQuery by using your callbacks as well, but I realized that any element is removed from it. Any advice?

TIA, Manuel :-)

**Comment by pixedelic** [comment]
Ok, I could simply put the SVG over the layer with a higher z-index value and fade it out on onAfter callback, but it is a little asynchronous.

**Comment by Gix075** [comment]
@pixedelic Hi Manuel I think that at now is impossible. I'm thinking to implement SVG spinners on the next releases.

**Comment by pixedelic** [comment]
Thank you!
