### ISSUE TITLE
$("#element").introLoader().stop(); not working

### ISSUE THREAD

**Issue by tanveer12332** [Gix075/jqueryIntroLoader#5]
Uncaught TypeError: $(...).introLoader is not a function(…)

**Comment by Gix075** [comment]
Hi, try to use the data method
var loader = $('#element').data('introLoader');
loader.stop();

Let me know.

**Comment by Gix075** [comment]
This is the demo of .stop() usage 
http://factory.brainleaf.eu/jqueryIntroLoader/demo/demo-simpleloader-startstop.html

**Comment by Gix075** [comment]
Have you solved?

**Comment by tanveer12332** [comment]
i use this code $('body').find('#element').remove();

**Comment by tanveer12332** [comment]
yes is working fine i use this function var loader = $('#element').data('introLoader');
loader.stop(); thanks u

**Comment by Gix075** [comment]
Perfect! Tnx for using my plugin!

**Comment by tanveer12332** [comment]
but not working in IE : Unable to get property 'stop' of undefined or null reference
