### ISSUE TITLE
'counterloader' not getting exit. Why?

### ISSUE THREAD

**Issue by himmatdb** [Gix075/jqueryIntroLoader#7]
'counterloader' not getting exit. 1 to 100% text display and stop there not showing page data. What is missing?

(Attached image)
![loading-issue](https://cloud.githubusercontent.com/assets/5779901/16142411/b6f9fe48-3482-11e6-876c-2beddcad50c2.jpg)

**Comment by Gix075** [comment]
Can I see your code?

**Comment by himmatdb** [comment]
ok .. I resolved. Jquery was getting colide.
